### ISSUE TITLE
POM is MIA

### ISSUE THREAD

**Issue by dkearns** [Imhotup/LibertyEiffel-Eclipse-Plugin#3]
[doug] eiffel/liberty-eiffel/LibertyEiffel-eclipse-plugin (git)-[master] % mvn clean verify  
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.383s
[INFO] Finished at: Fri Jun 10 03:26:29 AEST 2016
[INFO] Final Memory: 4M/110M
[INFO] ------------------------------------------------------------------------
[ERROR] The goal you specified requires a project to execute but there is no POM in this directory (/home/doug/projects/eiffel/liberty-eiffel/LibertyEiffel-eclipse-plugin). Please verify you invoked Maven from the correct directory. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MissingProjectException

**Comment by ch3ck** [comment]
@dkearns forgot to add it :-( Here is it: https://github.com/Imhotup/LibertyEiffel-Eclipse-Plugin/commit/8bf6b66a11f86ae208225ad1d87300723a62fb2e
